import type {
  MonitorCountryOption,
  MonitorHeroSlot,
  MonitorRoleOption,
  MonitorWidgetCapability,
} from "@/components/monitor/v2/types";

export const MONITOR_ROLE_OPTIONS: readonly MonitorRoleOption[] = [
  {
    id: "all",
    label: "Show All",
    description: "Full monitor view across pricing, logistics, outlooks, and signals.",
  },
  {
    id: "farmer",
    label: "Farmer",
    description: "Operational view with harvest, weather, export, and farm-relevant market context.",
  },
  {
    id: "trader",
    label: "Trader",
    description: "Trading view with broader market depth, logistics, policy, and signal pressure.",
  },
  {
    id: "broker",
    label: "Broker",
    description: "Flow and execution view focused on policy, logistics, corridor risk, and high-impact signals.",
  },
] as const;

export const MONITOR_COUNTRY_OPTIONS: readonly MonitorCountryOption[] = [
  {
    code: "US",
    label: "United States",
    short: "US",
    signalContext: ["us", "united states", "north america", "gulf", "pnw"],
  },
  {
    code: "UA",
    label: "Ukraine",
    short: "UA",
    signalContext: ["ukraine", "black sea", "eu", "europe", "romania", "bulgaria", "poland"],
  },
  {
    code: "BR",
    label: "Brazil",
    short: "BR",
    signalContext: ["brazil", "latam", "south america", "santos", "paranagua"],
  },
  {
    code: "AR",
    label: "Argentina",
    short: "AR",
    signalContext: ["argentina", "latam", "south america", "rosario"],
  },
] as const;

export const MONITOR_HERO_SLOTS: readonly MonitorHeroSlot[] = [
  {
    id: "command-bar",
    kind: "controls",
    title: "Command Bar",
    accepts: ["composite"],
    fixed: true,
  },
  {
    id: "kpi-strip",
    kind: "kpi",
    title: "KPI Strip",
    accepts: ["kpi"],
    fixed: true,
  },
  {
    id: "canvas",
    kind: "canvas",
    title: "Hero Canvas",
    accepts: ["map", "chart", "composite", "signal-list"],
    fixed: true,
  },
  {
    id: "feature-left",
    kind: "feature",
    title: "Feature Left",
    accepts: ["chart", "composite", "signal-list", "logistics", "outlook"],
    fixed: true,
  },
  {
    id: "feature-right",
    kind: "feature",
    title: "Feature Right",
    accepts: ["chart", "composite", "signal-list", "logistics", "outlook"],
    fixed: true,
  },
  {
    id: "media-primary",
    kind: "media",
    title: "Media Primary",
    accepts: ["media", "camera"],
    fixed: true,
  },
  {
    id: "media-secondary",
    kind: "media",
    title: "Media Secondary",
    accepts: ["media", "camera"],
    fixed: true,
  },
  {
    id: "watchlist",
    kind: "watchlist",
    title: "Watchlist",
    accepts: ["signal-list", "news-feed", "ranking-table"],
    fixed: true,
  },
] as const;

export const MONITOR_V2_WIDGET_CAPABILITIES: readonly MonitorWidgetCapability[] = [
  {
    id: "top-signals-priority",
    title: "Top Signals",
    type: "signal-list",
    topics: ["signals", "news"],
    roles: ["all", "farmer", "trader", "broker"],
    countries: ["GLOBAL"],
    maturity: "live",
    defaultGridSize: "l",
    maxGridSize: "xl",
    canLiveInGrid: true,
    canLiveInHero: true,
    heroSlots: ["feature-left", "watchlist"],
  },
  {
    id: "signal-watchlist",
    title: "Signal Watchlist",
    type: "signal-list",
    topics: ["signals", "logistics"],
    roles: ["all", "trader", "broker"],
    countries: ["GLOBAL"],
    maturity: "live",
    defaultGridSize: "m",
    maxGridSize: "l",
    canLiveInGrid: true,
    canLiveInHero: true,
    heroSlots: ["watchlist", "feature-right"],
  },
  {
    id: "fao-ffpi",
    title: "FAO FFPI",
    type: "chart",
    topics: ["markets", "macro"],
    roles: ["all", "farmer", "trader", "broker"],
    countries: ["GLOBAL"],
    maturity: "live",
    defaultGridSize: "m",
    maxGridSize: "l",
    canLiveInGrid: true,
    canLiveInHero: true,
    heroSlots: ["feature-left", "feature-right"],
  },
  {
    id: "global-spot",
    title: "Global Spot",
    type: "table",
    topics: ["markets"],
    roles: ["all", "farmer", "trader", "broker"],
    countries: ["GLOBAL"],
    maturity: "live",
    defaultGridSize: "l",
    maxGridSize: "xl",
    canLiveInGrid: true,
    canLiveInHero: true,
    heroSlots: ["feature-left", "feature-right"],
  },
  {
    id: "cbot-futures",
    title: "CBOT Futures",
    type: "table",
    topics: ["markets"],
    roles: ["all", "trader", "broker"],
    countries: ["GLOBAL"],
    maturity: "live",
    defaultGridSize: "l",
    maxGridSize: "xl",
    canLiveInGrid: true,
    canLiveInHero: true,
    heroSlots: ["feature-left", "feature-right"],
  },
  {
    id: "usda-nass",
    title: "USDA NASS",
    type: "chart",
    topics: ["markets", "outlook"],
    roles: ["all", "farmer", "trader"],
    countries: ["US"],
    maturity: "live",
    defaultGridSize: "m",
    maxGridSize: "l",
    canLiveInGrid: true,
    canLiveInHero: true,
    heroSlots: ["feature-left", "feature-right"],
  },
  {
    id: "ec-cereals",
    title: "EC Cereals",
    type: "table",
    topics: ["markets"],
    roles: ["all", "farmer", "trader", "broker"],
    countries: ["EU", "FR", "DE", "RO", "PL", "ES"],
    maturity: "fallback",
    defaultGridSize: "m",
    maxGridSize: "l",
    canLiveInGrid: true,
    canLiveInHero: true,
    heroSlots: ["feature-left", "feature-right"],
  },
  {
    id: "ec-oilseeds",
    title: "EC Oilseeds",
    type: "table",
    topics: ["markets"],
    roles: ["all", "farmer", "trader", "broker"],
    countries: ["EU", "FR", "DE", "RO", "PL", "ES"],
    maturity: "fallback",
    defaultGridSize: "m",
    maxGridSize: "l",
    canLiveInGrid: true,
    canLiveInHero: true,
    heroSlots: ["feature-left", "feature-right"],
  },
  {
    id: "eurostat-agri",
    title: "Eurostat Agri Price Indices",
    type: "chart",
    topics: ["markets", "macro"],
    roles: ["all", "farmer", "trader", "broker"],
    countries: ["EU", "FR", "DE", "RO", "PL", "ES"],
    maturity: "live",
    defaultGridSize: "m",
    maxGridSize: "l",
    canLiveInGrid: true,
    canLiveInHero: true,
    heroSlots: ["feature-left", "feature-right"],
  },
  {
    id: "imf-benchmarks",
    title: "IMF Benchmarks",
    type: "table",
    topics: ["markets", "macro"],
    roles: ["all", "trader", "broker"],
    countries: ["GLOBAL"],
    maturity: "live",
    defaultGridSize: "m",
    maxGridSize: "l",
    canLiveInGrid: true,
    canLiveInHero: true,
    heroSlots: ["feature-left", "feature-right"],
  },
  {
    id: "amis-balance",
    title: "AMIS Global Balance",
    type: "outlook",
    topics: ["outlook"],
    roles: ["all", "farmer", "trader"],
    countries: ["GLOBAL"],
    maturity: "live",
    defaultGridSize: "m",
    maxGridSize: "l",
    canLiveInGrid: true,
    canLiveInHero: true,
    heroSlots: ["feature-right"],
  },
  {
    id: "logistics-pressure-grid",
    title: "Logistics Pressure",
    type: "logistics",
    topics: ["logistics", "signals"],
    roles: ["all", "trader", "broker"],
    countries: ["GLOBAL"],
    maturity: "live",
    defaultGridSize: "m",
    maxGridSize: "l",
    canLiveInGrid: true,
    canLiveInHero: true,
    heroSlots: ["feature-right"],
  },
  {
    id: "hero-media-primary",
    title: "Hero Media Primary",
    type: "media",
    topics: ["media"],
    roles: ["all", "farmer", "trader", "broker"],
    countries: ["GLOBAL"],
    maturity: "experimental",
    defaultGridSize: "xl",
    maxGridSize: "xl",
    canLiveInGrid: false,
    canLiveInHero: true,
    heroSlots: ["media-primary"],
    videoOnly: true,
  },
  {
    id: "hero-media-secondary",
    title: "Hero Media Secondary",
    type: "camera",
    topics: ["media", "logistics"],
    roles: ["all", "farmer", "trader", "broker"],
    countries: ["GLOBAL"],
    maturity: "experimental",
    defaultGridSize: "m",
    maxGridSize: "m",
    canLiveInGrid: false,
    canLiveInHero: true,
    heroSlots: ["media-secondary"],
    videoOnly: true,
  },
] as const;
