import type { LiveVisualSourceConfig } from "./types";

// Wave 1 live visuals config (MVP): keep lightweight and fallback-friendly.
export const LIVE_VISUAL_SOURCES: LiveVisualSourceConfig[] = [
  {
    id: "black-sea-wind-map",
    title: "Black Sea Wind & Sea State",
    subtitle: "Near-live weather overlay for corridor risk",
    region: "Black Sea",
    category: "Weather",
    providerType: "embedded",
    sourceName: "Windy",
    url: "https://www.windy.com",
    embedUrl:
      "https://embed.windy.com/embed2.html?lat=44.40&lon=34.00&detailLat=44.40&detailLon=34.00&width=800&height=450&zoom=5&level=surface&overlay=wind&product=ecmwf&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&metricWind=default&metricTemp=default&radarRange=-1",
    externalUrl: "https://www.windy.com/44.400/34.000",
    enabled: true,
    priority: 120,
    statusHint: "LIVE",
    attribution: "Windy",
    tags: ["weather", "black sea", "shipping", "ports"],
  },
  {
    id: "noaa-atlantic-satellite",
    title: "North Atlantic Satellite Snapshot",
    subtitle: "Near-live weather watch for shipping lanes",
    region: "Global",
    category: "Weather",
    providerType: "image_refresh",
    sourceName: "NOAA GOES",
    url: "https://cdn.star.nesdis.noaa.gov",
    imageUrl: "https://cdn.star.nesdis.noaa.gov/GOES16/ABI/SECTOR/taw/GEOCOLOR/1000x1000.jpg",
    externalUrl: "https://www.star.nesdis.noaa.gov/GOES/sector.php?sat=G16&sector=taw",
    refreshIntervalSec: 300,
    enabled: true,
    priority: 110,
    statusHint: "REFRESH",
    attribution: "NOAA",
    tags: ["weather", "shipping", "atlantic"],
  },
  {
    id: "montreal-port-cameras",
    title: "Port of Montreal Cameras",
    subtitle: "Official port camera page (entry, waiting area, terminals)",
    region: "Americas",
    category: "Port",
    providerType: "external_link",
    sourceName: "Port of Montreal",
    url: "https://www.port-montreal.com/en/goods/real-time/cameras",
    externalUrl: "https://www.port-montreal.com/en/goods/real-time/cameras",
    enabled: true,
    priority: 85,
    statusHint: "EXTERNAL",
    attribution: "Port of Montreal",
    tags: ["port", "cameras", "grain-logistics", "americas"],
  },
  {
    id: "geelong-corio-quay-graincorp-cam",
    title: "Geelong / Corio Quay Grain Pier Cam",
    subtitle: "Public webcam page for Corio Quay / Graincorp bulk grain loading area",
    region: "Australia",
    category: "Port",
    providerType: "external_link",
    sourceName: "VRCA / OnlyGeelong",
    url: "https://www.onlygeelong.com.au/vrca-webcams",
    externalUrl: "https://www.onlygeelong.com.au/vrca-webcams",
    enabled: true,
    priority: 80,
    statusHint: "EXTERNAL",
    attribution: "VRCA / OnlyGeelong",
    tags: ["port", "grain-pier", "graincorp", "australia"],
  },
  {
    id: "rfdtv-grain-markets-youtube",
    title: "RFD-TV Grain Markets (YouTube)",
    subtitle: "Market commentary and grain-focused video feed",
    region: "Global",
    category: "Market Media",
    providerType: "embedded",
    sourceName: "YouTube / RFD-TV",
    url: "https://www.youtube.com/@RFDTV",
    embedUrl: "https://www.youtube.com/embed/videoseries?list=PLxAgXqEd7xfd9AhYwU3VzqzsUP_Wa4QF7",
    externalUrl: "https://www.youtube.com/@RFDTV",
    enabled: true,
    priority: 95,
    statusHint: "LIVE",
    attribution: "RFD-TV / YouTube",
    tags: ["market-media", "grain-markets", "youtube", "futures"],
  },
  {
    id: "agday-youtube-media",
    title: "AgDay Market Media",
    subtitle: "Public ag market video feed",
    region: "US",
    category: "Market Media",
    providerType: "embedded",
    sourceName: "AgDay YouTube",
    url: "https://www.youtube.com/",
    embedUrl: "https://www.youtube.com/embed/videoseries?list=PLvTM5d7T5l6mwnYBebH2HtRiqlDjhprde",
    externalUrl: "https://www.youtube.com/results?search_query=AgDay+Farm+Journal",
    enabled: false,
    priority: 70,
    statusHint: "LIVE",
    attribution: "AgDay",
    tags: ["market media", "grain", "youtube"],
  },
  {
    id: "rail-terminal-placeholder",
    title: "Rail Terminal Visual",
    subtitle: "Configurable rail operations source",
    region: "Global",
    category: "Rail",
    providerType: "external_link",
    sourceName: "Rail source placeholder",
    url: "https://www.railwaygazette.com/",
    externalUrl: "https://www.railwaygazette.com/",
    enabled: false,
    priority: 50,
    statusHint: "EXTERNAL",
    tags: ["rail", "logistics"],
  },
];
