import type { LiveVisualSourceConfig } from "./types";

// Wave 1 live visuals config (MVP): keep lightweight and fallback-friendly.
export const LIVE_VISUAL_SOURCES: LiveVisualSourceConfig[] = [
  {
    id: "black-sea-wind-map",
    title: "Black Sea Wind & Sea State",
    subtitle: "Near-live weather overlay for corridor risk",
    region: "Black Sea",
    category: "Weather",
    providerType: "embedded",
    sourceName: "Windy",
    url: "https://www.windy.com",
    embedUrl:
      "https://embed.windy.com/embed2.html?lat=44.40&lon=34.00&detailLat=44.40&detailLon=34.00&width=800&height=450&zoom=5&level=surface&overlay=wind&product=ecmwf&menu=&message=&marker=&calendar=&pressure=&type=map&location=coordinates&detail=&metricWind=default&metricTemp=default&radarRange=-1",
    externalUrl: "https://www.windy.com/44.400/34.000",
    enabled: true,
    priority: 100,
    statusHint: "LIVE",
    attribution: "Windy",
    tags: ["weather", "black sea", "logistics"],
  },
  {
    id: "rotterdam-port-cams",
    title: "Port of Rotterdam Cameras",
    subtitle: "Port and vessel operations visual context",
    region: "Europe",
    category: "Port",
    providerType: "external_link",
    sourceName: "Port of Rotterdam",
    url: "https://www.portofrotterdam.com/en/news-and-press-releases/webcams",
    externalUrl: "https://www.portofrotterdam.com/en/news-and-press-releases/webcams",
    enabled: true,
    priority: 90,
    statusHint: "EXTERNAL",
    attribution: "Port of Rotterdam",
    tags: ["port", "logistics", "europe"],
  },
  {
    id: "montreal-port-cams",
    title: "Port of Montreal Cameras",
    subtitle: "Real-time port activity page",
    region: "Americas",
    category: "Port",
    providerType: "external_link",
    sourceName: "Port of Montreal",
    url: "https://www.port-montreal.com/en/the-port-of-montreal/webcams",
    externalUrl: "https://www.port-montreal.com/en/the-port-of-montreal/webcams",
    enabled: true,
    priority: 80,
    statusHint: "EXTERNAL",
    attribution: "Port of Montreal",
    tags: ["port", "americas", "shipping"],
  },
  {
    id: "goes-atlantic-snapshot",
    title: "North Atlantic Satellite Snapshot",
    subtitle: "Near-live weather watch for shipping lanes",
    region: "Global",
    category: "Weather",
    providerType: "image_refresh",
    sourceName: "NOAA GOES",
    url: "https://cdn.star.nesdis.noaa.gov",
    imageUrl: "https://cdn.star.nesdis.noaa.gov/GOES16/ABI/SECTOR/taw/GEOCOLOR/1000x1000.jpg",
    externalUrl: "https://www.star.nesdis.noaa.gov/GOES/sector.php?sat=G16&sector=taw",
    refreshIntervalSec: 300,
    enabled: true,
    priority: 70,
    statusHint: "REFRESH",
    attribution: "NOAA",
    tags: ["weather", "shipping", "atlantic"],
  },
  {
    id: "market-media-live",
    title: "Market Media Live",
    subtitle: "Live market coverage and interviews",
    region: "Global",
    category: "Market Media",
    providerType: "external_link",
    sourceName: "Bloomberg TV",
    url: "https://www.youtube.com/@BloombergTV/live",
    externalUrl: "https://www.youtube.com/@BloombergTV/live",
    enabled: true,
    priority: 60,
    statusHint: "EXTERNAL",
    attribution: "Bloomberg TV",
    tags: ["market media", "macro", "live"],
  },
  {
    id: "rail-terminal-placeholder",
    title: "Rail Terminal Visual",
    subtitle: "Configurable rail operations source",
    region: "Global",
    category: "Rail",
    providerType: "external_link",
    sourceName: "Rail source placeholder",
    url: "https://www.railwaygazette.com/",
    externalUrl: "https://www.railwaygazette.com/",
    enabled: false,
    priority: 50,
    statusHint: "EXTERNAL",
    tags: ["rail", "logistics"],
  },
];
