import type { MonitorGridWidgetMeta } from "@/components/monitor/grid/types";

export const MONITOR_GRID_WIDGET_REGISTRY: Record<string, MonitorGridWidgetMeta> = {
  "top-signals-priority": {
    id: "top-signals-priority",
    title: "Top Signals",
    audience: ["all", "farmer", "trader", "broker"],
    geo: ["GLOBAL"],
    priority: "secondary",
    maturity: "live",
    defaultSpan: "wide",
    allowHide: true,
  },
  "signal-watchlist": {
    id: "signal-watchlist",
    title: "Signal Watchlist",
    audience: ["all", "trader", "broker"],
    geo: ["GLOBAL"],
    priority: "secondary",
    maturity: "live",
    defaultSpan: "standard",
    allowHide: true,
  },
  "fao-ffpi": {
    id: "fao-ffpi",
    title: "FAO FFPI",
    audience: ["all", "farmer", "trader", "broker"],
    geo: ["GLOBAL"],
    priority: "secondary",
    maturity: "live",
    defaultSpan: "standard",
    allowHide: true,
  },
  "usda-nass": {
    id: "usda-nass",
    title: "USDA NASS",
    audience: ["all", "farmer", "trader"],
    geo: ["US"],
    priority: "secondary",
    maturity: "live",
    defaultSpan: "standard",
    allowHide: true,
  },
  "eurostat-agri": {
    id: "eurostat-agri",
    title: "Eurostat Agri Price Indices",
    audience: ["all", "farmer", "trader", "broker"],
    geo: ["EU", "FR", "DE", "RO", "PL", "ES"],
    priority: "secondary",
    maturity: "live",
    defaultSpan: "standard",
    allowHide: true,
  },
  "imf-benchmarks": {
    id: "imf-benchmarks",
    title: "IMF Benchmarks",
    audience: ["all", "trader", "broker"],
    geo: ["GLOBAL"],
    priority: "secondary",
    maturity: "live",
    defaultSpan: "standard",
    allowHide: true,
  },
  "amis-balance": {
    id: "amis-balance",
    title: "AMIS Global Balance",
    audience: ["all", "farmer", "trader"],
    geo: ["GLOBAL"],
    priority: "deep",
    maturity: "live",
    defaultSpan: "standard",
    allowHide: true,
  },
  "logistics-pressure-grid": {
    id: "logistics-pressure-grid",
    title: "Logistics Pressure",
    audience: ["all", "trader", "broker"],
    geo: ["GLOBAL"],
    priority: "secondary",
    maturity: "live",
    defaultSpan: "standard",
    allowHide: true,
  },
};
